services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: reveski
    ports:
      - "5433:5432"
    volumes:
      - reve-ski-db:/var/lib/postgresql/data

volumes:
  reve-ski-db:
